#!/bin/bash
set -e

# Define data directory structure
DATA_DIR="/data"
CONF_DIR="${DST_CONF_DIR:-DoNotStarveTogether}"
CLUSTER_DIR="${DST_CLUSTER_DIR:-Cluster_1}"
CLUSTER_PATH="${DATA_DIR}/${CONF_DIR}/${CLUSTER_DIR}"

# Set default values for env vars
CLUSTER_NAME="${DST_CLUSTER_NAME:-DST Dedicated Server}"
CLUSTER_DESC="${DST_CLUSTER_DESC:-A Don't Starve Together server running on Docker}"
CLUSTER_PASS="${DST_CLUSTER_PASS:-}"
CLUSTER_INTENTION="${DST_CLUSTER_INTENTION:-cooperative}"
GAME_MODE="${DST_GAME_MODE:-survival}"
MAX_PLAYERS="${DST_MAX_PLAYERS:-6}"
PVP="${DST_PVP:-false}"
PAUSE_WHEN_EMPTY="${DST_PAUSE_WHEN_EMPTY:-true}"
VOTE_ENABLED="${DST_VOTE_ENABLED:-true}"
TICK_RATE="${DST_TICK_RATE:-30}"
SHARD_MODE="${DST_SHARD_MODE:-Single}" # Options: Single, Master, Caves, Both
CLUSTER_KEY="${DST_CLUSTER_KEY:-dst_cluster_key}"
MASTER_IP="${DST_MASTER_IP:-127.0.0.1}"
MASTER_PORT="${DST_MASTER_PORT:-10888}"
SERVER_PORT="${DST_SERVER_PORT:-10999}"
CAVES_PORT="${DST_CAVES_PORT:-11000}"

echo "============================================="
echo "Starting DST Server Entrypoint..."
echo "SHARD_MODE: ${SHARD_MODE}"
echo "CLUSTER_PATH: ${CLUSTER_PATH}"
echo "============================================="

# Ensure data directory is writable
if [ ! -w "${DATA_DIR}" ]; then
    echo "ERROR: Data directory '${DATA_DIR}' is not writable!"
    echo "Please check folder permissions on the host."
    echo "Make sure the mounted folder is writable by UID 1000 (steam) or GID 1000 (steam)."
    exit 1
fi


# 1. Handle Auto-Update
if [ "${DST_AUTO_UPDATE}" = "true" ]; then
    echo "Checking for game updates..."
    /usr/games/steamcmd +force_install_dir /opt/dst-server +login anonymous +app_update 343050 validate +quit
    echo "Update complete."
fi

# 2. Ensure directories exist
mkdir -p "${CLUSTER_PATH}/Master"
mkdir -p "${CLUSTER_PATH}/Caves"

# 3. Handle Cluster Token
if [ -n "${DST_CLUSTER_TOKEN}" ]; then
    echo "Writing cluster token..."
    echo "${DST_CLUSTER_TOKEN}" > "${CLUSTER_PATH}/cluster_token.txt"
elif [ ! -f "${CLUSTER_PATH}/cluster_token.txt" ]; then
    echo "WARNING: DST_CLUSTER_TOKEN is not set and no cluster_token.txt exists!"
    echo "The server might not be able to authenticate with Klei servers."
fi

# 4. Generate cluster.ini
SHARD_ENABLED="false"
if [ "${SHARD_MODE}" != "Single" ]; then
    SHARD_ENABLED="true"
fi

echo "Generating cluster.ini..."
cat <<EOF > "${CLUSTER_PATH}/cluster.ini"
[GAMEPLAY]
game_mode = ${GAME_MODE}
max_players = ${MAX_PLAYERS}
pvp = ${PVP}
pause_when_empty = ${PAUSE_WHEN_EMPTY}
vote_enabled = ${VOTE_ENABLED}

[NETWORK]
cluster_name = ${CLUSTER_NAME}
cluster_description = ${CLUSTER_DESC}
cluster_password = ${CLUSTER_PASS}
cluster_intention = ${CLUSTER_INTENTION}
tick_rate = ${TICK_RATE}

[MISC]
console_enabled = true
max_snapshots = 6

[SHARD]
shard_enabled = ${SHARD_ENABLED}
bind_ip = 0.0.0.0
master_ip = ${MASTER_IP}
master_port = ${MASTER_PORT}
cluster_key = ${CLUSTER_KEY}
EOF

# 5. Helper function to generate mod files
setup_mods() {
    local shard_dir=$1
    if [ -n "${DST_MODS}" ]; then
        echo "Setting up mods for ${shard_dir}..."
        
        # Write/Update download setup (global to game installation)
        local mod_setup_file="/opt/dst-server/mods/dedicated_server_mods_setup.lua"
        echo "-- Generated by Docker entrypoint on startup" > "$mod_setup_file"
        
        # Write enable setup (local to shard folder)
        local mod_override_file="${CLUSTER_PATH}/${shard_dir}/modoverrides.lua"
        
        if [ ! -f "$mod_override_file" ]; then
            echo "-- Generated by Docker entrypoint on startup" > "$mod_override_file"
            echo "return {" >> "$mod_override_file"
        fi
        
        # Split mods and iterate
        IFS=',' read -ra MOD_IDS <<< "${DST_MODS}"
        for mod_id in "${MOD_IDS[@]}"; do
            # Trim whitespace
            mod_id=$(echo "${mod_id}" | xargs)
            if [ -n "${mod_id}" ]; then
                echo "ServerModSetup(\"${mod_id}\")" >> "$mod_setup_file"
                
                # Only add if we're creating modoverrides for the first time
                if [ ! -f "${CLUSTER_PATH}/${shard_dir}/modoverrides.lua.bak" ]; then
                    # Check if mod is already in modoverrides
                    if ! grep -q "workshop-${mod_id}" "$mod_override_file" 2>/dev/null; then
                        echo "  [\"workshop-${mod_id}\"] = { enabled = true }," >> "$mod_override_file"
                    fi
                fi
            fi
        done
        
        if [ ! -f "${CLUSTER_PATH}/${shard_dir}/modoverrides.lua.bak" ]; then
            echo "}" >> "$mod_override_file"
            # create backup to mark that we generated it
            touch "${CLUSTER_PATH}/${shard_dir}/modoverrides.lua.bak"
        fi
    fi
}

# 6. Generate Shard server.ini and worldgenoverride.lua files
# Master configuration
if [ "${SHARD_MODE}" = "Master" ] || [ "${SHARD_MODE}" = "Both" ] || [ "${SHARD_MODE}" = "Single" ]; then
    echo "Generating Master/server.ini..."
    cat <<EOF > "${CLUSTER_PATH}/Master/server.ini"
[SHARD]
is_master = true
name = Master
id = 1

[STEAM]
master_server_port = 27018
authentication_port = 8768

[NETWORK]
server_port = ${SERVER_PORT}
EOF

    # Default worldgen for master
    if [ ! -f "${CLUSTER_PATH}/Master/worldgenoverride.lua" ]; then
        echo "Creating default Master/worldgenoverride.lua..."
        cat <<EOF > "${CLUSTER_PATH}/Master/worldgenoverride.lua"
return {
  override_enabled = true,
  preset = "SURVIVAL_TOGETHER",
}
EOF
    fi
    setup_mods "Master"
fi

# Caves configuration
if [ "${SHARD_MODE}" = "Caves" ] || [ "${SHARD_MODE}" = "Both" ]; then
    echo "Generating Caves/server.ini..."
    
    # Avoid port collision with Master if running in the same container (Both)
    caves_master_port=27018
    caves_auth_port=8768
    caves_srv_port=${SERVER_PORT}
    
    if [ "${SHARD_MODE}" = "Both" ]; then
        caves_master_port=27019
        caves_auth_port=8769
        caves_srv_port=${CAVES_PORT}
    fi

    cat <<EOF > "${CLUSTER_PATH}/Caves/server.ini"
[SHARD]
is_master = false
name = Caves
id = 2

[STEAM]
master_server_port = ${caves_master_port}
authentication_port = ${caves_auth_port}

[NETWORK]
server_port = ${caves_srv_port}
EOF

    # Default worldgen for caves
    if [ ! -f "${CLUSTER_PATH}/Caves/worldgenoverride.lua" ]; then
        echo "Creating default Caves/worldgenoverride.lua..."
        cat <<EOF > "${CLUSTER_PATH}/Caves/worldgenoverride.lua"
return {
  override_enabled = true,
  preset = "DST_CAVE",
}
EOF
    fi
    setup_mods "Caves"
fi

# 7. Execution and Process Monitoring (Graceful Shutdown)
master_pid=""
caves_pid=""

cleanup() {
    echo "Received shutdown signal. Stopping DST Server processes gracefully..."
    if [ -n "$master_pid" ]; then
        echo "Stopping Master shard (PID: $master_pid)..."
        kill -SIGTERM "$master_pid" 2>/dev/null
    fi
    if [ -n "$caves_pid" ]; then
        echo "Stopping Caves shard (PID: $caves_pid)..."
        kill -SIGTERM "$caves_pid" 2>/dev/null
    fi
    
    # Wait for processes to exit (DST server saves world on SIGTERM)
    [ -n "$master_pid" ] && wait "$master_pid" 2>/dev/null
    [ -n "$caves_pid" ] && wait "$caves_pid" 2>/dev/null
    echo "Server processes stopped. Safe to exit container."
    exit 0
}

trap cleanup SIGINT SIGTERM

# Run servers
cd /opt/dst-server/bin64

if [ "${SHARD_MODE}" = "Single" ]; then
    echo "Starting Master server (shard communication disabled)..."
    ./dontstarve_dedicated_server_nullrenderer_x64 \
        -console \
        -persistent_storage_root "${DATA_DIR}" \
        -conf_dir "${CONF_DIR}" \
        -cluster "${CLUSTER_DIR}" \
        -shard Master &
    master_pid=$!
    wait "$master_pid"

elif [ "${SHARD_MODE}" = "Master" ]; then
    echo "Starting Master shard..."
    ./dontstarve_dedicated_server_nullrenderer_x64 \
        -console \
        -persistent_storage_root "${DATA_DIR}" \
        -conf_dir "${CONF_DIR}" \
        -cluster "${CLUSTER_DIR}" \
        -shard Master &
    master_pid=$!
    wait "$master_pid"

elif [ "${SHARD_MODE}" = "Caves" ]; then
    echo "Starting Caves shard..."
    ./dontstarve_dedicated_server_nullrenderer_x64 \
        -console \
        -persistent_storage_root "${DATA_DIR}" \
        -conf_dir "${CONF_DIR}" \
        -cluster "${CLUSTER_DIR}" \
        -shard Caves &
    caves_pid=$!
    wait "$caves_pid"

elif [ "${SHARD_MODE}" = "Both" ]; then
    echo "Starting both Master and Caves shards inside this container..."
    
    echo "Launching Master shard..."
    ./dontstarve_dedicated_server_nullrenderer_x64 \
        -console \
        -persistent_storage_root "${DATA_DIR}" \
        -conf_dir "${CONF_DIR}" \
        -cluster "${CLUSTER_DIR}" \
        -shard Master &
    master_pid=$!
    
    echo "Waiting 15 seconds before starting Caves shard to let Master initialize..."
    sleep 15
    
    echo "Launching Caves shard..."
    ./dontstarve_dedicated_server_nullrenderer_x64 \
        -console \
        -persistent_storage_root "${DATA_DIR}" \
        -conf_dir "${CONF_DIR}" \
        -cluster "${CLUSTER_DIR}" \
        -shard Caves &
    caves_pid=$!
    
    # Wait for both background processes
    wait "$master_pid" "$caves_pid"
fi
