#!/bin/bash
set -e

# ============================================
# DST Dedicated Server - Docker Entrypoint
# ============================================

STEAMCMD_PATH="${STEAMCMD_PATH:-/usr/bin/steamcmd}"
INSTALL_DIR="/opt/dst-server"

# Define data directory structure
DATA_DIR="/data"
CONF_DIR="${DST_CONF_DIR:-DoNotStarveTogether}"
CLUSTER_DIR="${DST_CLUSTER_DIR:-Cluster_1}"
CLUSTER_PATH="${DATA_DIR}/${CONF_DIR}/${CLUSTER_DIR}"

# Set default values for env vars
CLUSTER_NAME="${DST_CLUSTER_NAME:-DST Dedicated Server}"
CLUSTER_DESC="${DST_CLUSTER_DESC:-A Don't Starve Together server running on Docker}"
CLUSTER_PASS="${DST_CLUSTER_PASS:-}"
CLUSTER_INTENTION="${DST_CLUSTER_INTENTION:-cooperative}"
GAME_MODE="${DST_GAME_MODE:-survival}"
MAX_PLAYERS="${DST_MAX_PLAYERS:-6}"
PVP="${DST_PVP:-false}"
PAUSE_WHEN_EMPTY="${DST_PAUSE_WHEN_EMPTY:-true}"
VOTE_ENABLED="${DST_VOTE_ENABLED:-true}"
TICK_RATE="${DST_TICK_RATE:-30}"
SHARD_MODE="${DST_SHARD_MODE:-Single}" # Options: Single, Master, Caves, Both
CLUSTER_KEY="${DST_CLUSTER_KEY:-dst_cluster_key}"
MASTER_IP="${DST_MASTER_IP:-127.0.0.1}"
MASTER_PORT="${DST_MASTER_PORT:-10888}"
SERVER_PORT="${DST_SERVER_PORT:-10999}"
CAVES_PORT="${DST_CAVES_PORT:-11000}"

echo "============================================="
echo " Don't Starve Together - Dedicated Server"
echo "============================================="
echo "SHARD_MODE: ${SHARD_MODE}"
echo "CLUSTER_PATH: ${CLUSTER_PATH}"
echo "============================================="

# --- 0. Ensure directories exist and have correct ownership ---
mkdir -p "${INSTALL_DIR}" "${DATA_DIR}" "${CLUSTER_PATH}/Master" "${CLUSTER_PATH}/Caves"
mkdir -p /home/steam/.steam/sdk64 /home/steam/.steam/sdk32 /home/steam/.steam/root /home/steam/Steam/logs
chown -R steam:steam /home/steam "${INSTALL_DIR}" "${DATA_DIR}"

# --- 1. Install / Update Game via SteamCMD ---
# Game is downloaded at first startup (or updated if DST_AUTO_UPDATE=true)
# This runs as the steam user to avoid permission issues
if [ "${DST_AUTO_UPDATE}" = "true" ] || [ ! -f "${INSTALL_DIR}/bin64/dontstarve_dedicated_server_nullrenderer_x64" ]; then
    echo "Installing/Updating DST Dedicated Server files..."

    RETRY_COUNT=0
    MAX_RETRIES=5

    while true; do
        if su steam -s /bin/bash -c "${STEAMCMD_PATH} +force_install_dir ${INSTALL_DIR} +login anonymous +app_update 343050 validate +quit"; then
            echo "Game install/update successful!"
            break
        else
            RETRY_COUNT=$((RETRY_COUNT + 1))
            if [ $RETRY_COUNT -ge $MAX_RETRIES ]; then
                echo "ERROR: SteamCMD failed after ${MAX_RETRIES} attempts. Exiting."
                exit 1
            fi
            echo "SteamCMD failed (Attempt ${RETRY_COUNT}/${MAX_RETRIES}). Retrying in 10 seconds..."
            sleep 10
        fi
    done
fi

# Ensure game files are owned by steam after install/update
chown -R steam:steam "${INSTALL_DIR}"

# --- 2. Handle Cluster Token ---
if [ -n "${DST_CLUSTER_TOKEN}" ]; then
    echo "Writing cluster token..."
    echo "${DST_CLUSTER_TOKEN}" > "${CLUSTER_PATH}/cluster_token.txt"
elif [ ! -f "${CLUSTER_PATH}/cluster_token.txt" ]; then
    echo "WARNING: DST_CLUSTER_TOKEN is not set and no cluster_token.txt exists!"
    echo "The server will not be able to authenticate with Klei servers."
fi

# --- 3. Generate cluster.ini ---
SHARD_ENABLED="false"
if [ "${SHARD_MODE}" != "Single" ]; then
    SHARD_ENABLED="true"
fi

echo "Generating cluster.ini..."
cat <<EOF > "${CLUSTER_PATH}/cluster.ini"
[GAMEPLAY]
game_mode = ${GAME_MODE}
max_players = ${MAX_PLAYERS}
pvp = ${PVP}
pause_when_empty = ${PAUSE_WHEN_EMPTY}
vote_enabled = ${VOTE_ENABLED}

[NETWORK]
cluster_name = ${CLUSTER_NAME}
cluster_description = ${CLUSTER_DESC}
cluster_password = ${CLUSTER_PASS}
cluster_intention = ${CLUSTER_INTENTION}
tick_rate = ${TICK_RATE}

[MISC]
console_enabled = true
max_snapshots = 6

[SHARD]
shard_enabled = ${SHARD_ENABLED}
bind_ip = 0.0.0.0
master_ip = ${MASTER_IP}
master_port = ${MASTER_PORT}
cluster_key = ${CLUSTER_KEY}
EOF

# --- 4. Helper function to generate mod files ---
setup_mods() {
    local shard_dir=$1
    if [ -n "${DST_MODS}" ]; then
        echo "Setting up mods for ${shard_dir}..."

        # Write/Update download setup (global to game installation)
        local mod_setup_file="${INSTALL_DIR}/mods/dedicated_server_mods_setup.lua"
        echo "-- Generated by Docker entrypoint on startup" > "$mod_setup_file"

        # Write enable setup (per-shard folder)
        local mod_override_file="${CLUSTER_PATH}/${shard_dir}/modoverrides.lua"

        if [ ! -f "$mod_override_file" ]; then
            echo "-- Generated by Docker entrypoint on startup" > "$mod_override_file"
            echo "return {" >> "$mod_override_file"
        fi

        # Split mods and iterate
        IFS=',' read -ra MOD_IDS <<< "${DST_MODS}"
        for mod_id in "${MOD_IDS[@]}"; do
            # Trim whitespace
            mod_id=$(echo "${mod_id}" | xargs)
            if [ -n "${mod_id}" ]; then
                echo "ServerModSetup(\"${mod_id}\")" >> "$mod_setup_file"

                # Only add if we're creating modoverrides for the first time
                if [ ! -f "${CLUSTER_PATH}/${shard_dir}/modoverrides.lua.bak" ]; then
                    if ! grep -q "workshop-${mod_id}" "$mod_override_file" 2>/dev/null; then
                        echo "  [\"workshop-${mod_id}\"] = { enabled = true }," >> "$mod_override_file"
                    fi
                fi
            fi
        done

        if [ ! -f "${CLUSTER_PATH}/${shard_dir}/modoverrides.lua.bak" ]; then
            echo "}" >> "$mod_override_file"
            # Create marker to prevent overwriting on next boot
            touch "${CLUSTER_PATH}/${shard_dir}/modoverrides.lua.bak"
        fi
    fi
}

# --- 5. Generate Shard server.ini and worldgenoverride.lua ---
# Master configuration
if [ "${SHARD_MODE}" = "Master" ] || [ "${SHARD_MODE}" = "Both" ] || [ "${SHARD_MODE}" = "Single" ]; then
    echo "Generating Master/server.ini..."
    cat <<EOF > "${CLUSTER_PATH}/Master/server.ini"
[SHARD]
is_master = true
name = Master
id = 1

[STEAM]
master_server_port = 27018
authentication_port = 8768

[NETWORK]
server_port = ${SERVER_PORT}
EOF

    # Default worldgen for master (only if not already customized)
    if [ ! -f "${CLUSTER_PATH}/Master/worldgenoverride.lua" ]; then
        echo "Creating default Master/worldgenoverride.lua..."
        cat <<EOF > "${CLUSTER_PATH}/Master/worldgenoverride.lua"
return {
  override_enabled = true,
  preset = "SURVIVAL_TOGETHER",
}
EOF
    fi
    setup_mods "Master"
fi

# Caves configuration
if [ "${SHARD_MODE}" = "Caves" ] || [ "${SHARD_MODE}" = "Both" ]; then
    echo "Generating Caves/server.ini..."

    # Avoid port collision with Master if running in the same container (Both mode)
    caves_master_port=27018
    caves_auth_port=8768
    caves_srv_port=${SERVER_PORT}

    if [ "${SHARD_MODE}" = "Both" ]; then
        caves_master_port=27019
        caves_auth_port=8769
        caves_srv_port=${CAVES_PORT}
    fi

    cat <<EOF > "${CLUSTER_PATH}/Caves/server.ini"
[SHARD]
is_master = false
name = Caves
id = 2

[STEAM]
master_server_port = ${caves_master_port}
authentication_port = ${caves_auth_port}

[NETWORK]
server_port = ${caves_srv_port}
EOF

    # Default worldgen for caves (only if not already customized)
    if [ ! -f "${CLUSTER_PATH}/Caves/worldgenoverride.lua" ]; then
        echo "Creating default Caves/worldgenoverride.lua..."
        cat <<EOF > "${CLUSTER_PATH}/Caves/worldgenoverride.lua"
return {
  override_enabled = true,
  preset = "DST_CAVE",
}
EOF
    fi
    setup_mods "Caves"
fi

# Ensure all generated config files are owned by steam
chown -R steam:steam "${DATA_DIR}"

# --- 6. Execution and Process Monitoring (Graceful Shutdown) ---
master_pid=""
caves_pid=""

cleanup() {
    echo "Received shutdown signal. Stopping DST Server processes gracefully..."
    if [ -n "$master_pid" ]; then
        echo "Stopping Master shard (PID: $master_pid)..."
        kill -SIGTERM "$master_pid" 2>/dev/null
    fi
    if [ -n "$caves_pid" ]; then
        echo "Stopping Caves shard (PID: $caves_pid)..."
        kill -SIGTERM "$caves_pid" 2>/dev/null
    fi

    # Wait for processes to exit (DST server saves world on SIGTERM)
    [ -n "$master_pid" ] && wait "$master_pid" 2>/dev/null
    [ -n "$caves_pid" ] && wait "$caves_pid" 2>/dev/null
    echo "Server processes stopped. Safe to exit container."
    exit 0
}

trap cleanup SIGINT SIGTERM

# --- Run the server as the steam user ---
DST_BIN="${INSTALL_DIR}/bin64"

if [ "${SHARD_MODE}" = "Single" ]; then
    echo "Starting Master server (shard communication disabled)..."
    su steam -s /bin/bash -c "${DST_BIN}/dontstarve_dedicated_server_nullrenderer_x64 \
        -console \
        -persistent_storage_root ${DATA_DIR} \
        -conf_dir ${CONF_DIR} \
        -cluster ${CLUSTER_DIR} \
        -shard Master" &
    master_pid=$!
    wait "$master_pid"

elif [ "${SHARD_MODE}" = "Master" ]; then
    echo "Starting Master shard..."
    su steam -s /bin/bash -c "${DST_BIN}/dontstarve_dedicated_server_nullrenderer_x64 \
        -console \
        -persistent_storage_root ${DATA_DIR} \
        -conf_dir ${CONF_DIR} \
        -cluster ${CLUSTER_DIR} \
        -shard Master" &
    master_pid=$!
    wait "$master_pid"

elif [ "${SHARD_MODE}" = "Caves" ]; then
    echo "Starting Caves shard..."
    su steam -s /bin/bash -c "${DST_BIN}/dontstarve_dedicated_server_nullrenderer_x64 \
        -console \
        -persistent_storage_root ${DATA_DIR} \
        -conf_dir ${CONF_DIR} \
        -cluster ${CLUSTER_DIR} \
        -shard Caves" &
    caves_pid=$!
    wait "$caves_pid"

elif [ "${SHARD_MODE}" = "Both" ]; then
    echo "Starting both Master and Caves shards inside this container..."

    echo "Launching Master shard..."
    su steam -s /bin/bash -c "${DST_BIN}/dontstarve_dedicated_server_nullrenderer_x64 \
        -console \
        -persistent_storage_root ${DATA_DIR} \
        -conf_dir ${CONF_DIR} \
        -cluster ${CLUSTER_DIR} \
        -shard Master" &
    master_pid=$!

    echo "Waiting 15 seconds before starting Caves shard to let Master initialize..."
    sleep 15

    echo "Launching Caves shard..."
    su steam -s /bin/bash -c "${DST_BIN}/dontstarve_dedicated_server_nullrenderer_x64 \
        -console \
        -persistent_storage_root ${DATA_DIR} \
        -conf_dir ${CONF_DIR} \
        -cluster ${CLUSTER_DIR} \
        -shard Caves" &
    caves_pid=$!

    # Wait for both background processes
    wait "$master_pid" "$caves_pid"
fi
